{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a6bf8c77",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package punkt to\n",
      "[nltk_data]     C:\\Users\\ankit\\AppData\\Roaming\\nltk_data...\n",
      "[nltk_data]   Package punkt is already up-to-date!\n"
     ]
    }
   ],
   "source": [
    "from bs4 import BeautifulSoup\n",
    "from urllib.request import urlopen, Request\n",
    "import os\n",
    "import pandas as pd\n",
    "from pandas.plotting import lag_plot\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline\n",
    "from nltk.sentiment.vader import SentimentIntensityAnalyzer\n",
    "from datetime import datetime\n",
    "import yfinance as yf\n",
    "from flask import Flask, render_template, request, flash, redirect, url_for\n",
    "from alpha_vantage.timeseries import TimeSeries\n",
    "from statsmodels.tsa.arima_model import ARIMA\n",
    "from sklearn.metrics import mean_squared_error\n",
    "import matplotlib.pyplot as plt\n",
    "plt.style.use('ggplot')\n",
    "import math, random\n",
    "import preprocessor as p\n",
    "import re\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from textblob import TextBlob\n",
    "import constants as ct\n",
    "import nltk\n",
    "nltk.download('punkt')\n",
    "\n",
    "import warnings"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "e6a5dbe8",
   "metadata": {},
   "outputs": [],
   "source": [
    "trading_url_int = 'https://finviz.com/quote.ashx?t='\n",
    "news_tables = {}\n",
    "tickers = ['AMZN', 'TSLA', 'GOOG']\n",
    "\n",
    "for ticker in tickers:\n",
    "    url = trading_url_int + ticker\n",
    "    req = Request(url=url,headers={'user-agent': 'my-app/1.0.0'})\n",
    "    response = urlopen(req)\n",
    "    \n",
    "    html = BeautifulSoup(response)\n",
    "    \n",
    "    news_table = html.find(id='news-table')\n",
    "    \n",
    "    news_tables[ticker] = news_table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "93e43c43",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Amazon, Microsoft Swoop In on $24 Billion India Farm-Data Trove\n",
      "Sep-16-21 10:30PM  \n",
      "Amazon (AMZN) Gains As Market Dips: What You Should Know\n",
      "05:45PM  \n",
      "10 Tech Stocks to Invest in Today According to Thomas E. Claugus GMT Capital\n",
      "04:39PM  \n",
      "FTC, Biden Antitrust Enforcement Push Takes On Amazon, Google  And The Supreme Court\n",
      "04:01PM  \n"
     ]
    }
   ],
   "source": [
    "amzn = news_tables['AMZN']\n",
    "amzn_tr = amzn.findAll('tr')\n",
    "\n",
    "for i, table_row in enumerate(amzn_tr):\n",
    "    a_text = table_row.a.text\n",
    "    td_text = table_row.td.text\n",
    "    print(a_text)\n",
    "    print(td_text)\n",
    "    if i == 3:\n",
    "        break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "84144eae",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '10:30PM',\n",
       "  'Amazon, Microsoft Swoop In on $24 Billion India Farm-Data Trove'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '05:45PM',\n",
       "  'Amazon (AMZN) Gains As Market Dips: What You Should Know'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '04:39PM',\n",
       "  '10 Tech Stocks to Invest in Today According to Thomas E. Claugus GMT Capital'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '04:01PM',\n",
       "  'FTC, Biden Antitrust Enforcement Push Takes On Amazon, Google  And The Supreme Court'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '01:49PM',\n",
       "  'Co-op criticised after announcing new partnership with Amazon in bid to double online sales'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '01:45PM',\n",
       "  'Amazon Plans Beauty Extravaganza To Target Early Holiday Shoppers'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '12:00PM',\n",
       "  \"Amazon's Latest Grocery Store Competes WithAmazon\"],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '10:28AM',\n",
       "  '3 Top Growth Stocks You Can Buy and Hold Forever'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '10:25AM',\n",
       "  'Is Google Stock A Buy? Internet Search Giant Tops Among FANG Stocks In 2021'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '10:20AM',\n",
       "  'Is Snowflake Stock A Buy? Data Analytics Specialist Rides Cloud Computing Wave'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '09:53AM',\n",
       "  '7 best VPN services for streaming securely in 2021'],\n",
       " ['AMZN', 'Sep-16-21', '09:22AM', 'Is Roku Stock a Buy?'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '09:20AM',\n",
       "  \"'Buy Now, Pay Later' Consumer Financing Takes On Credit Cards\"],\n",
       " ['AMZN', 'Sep-16-21', '09:15AM', '3 Stocks You Can Keep Forever'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '09:01AM',\n",
       "  'Retail Sales Surprise Amid Strong Online Sales; Amazon Near Buy Point'],\n",
       " ['AMZN', 'Sep-16-21', '08:41AM', '4 Struggling Stocks to Buy at a Discount'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '08:36AM',\n",
       "  'Crypto Bull Steve Cohen is Buying These 10 Stocks'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '08:24AM',\n",
       "  'Better Fintech Stock: Robinhood vs. Affirm'],\n",
       " ['AMZN', 'Sep-16-21', '08:07AM', '3 Value Stocks to Buy in September'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '07:15AM',\n",
       "  'Why All the Interest in Buy Now, Pay Later?'],\n",
       " ['AMZN', 'Sep-16-21', '06:40AM', '2 Smart Stocks to Buy and Hold Forever'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '06:13AM',\n",
       "  'Supermarket chain Co-op warns supply disruption to hit profits'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '06:00AM',\n",
       "  'Metaverse raises scary question on surveillance of users: Kai-Fu Lee'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '04:49AM',\n",
       "  'Amazon to more than double payroll in Spain to 25,000 by 2025'],\n",
       " ['AMZN',\n",
       "  'Sep-16-21',\n",
       "  '02:00AM',\n",
       "  'Co-op announces acceleration of online strategy'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '10:16PM',\n",
       "  'Forget fourth stimulus  these stocks offer income checks growing as fast as 11%'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '10:01PM',\n",
       "  'Blue-Collar Worker App Becomes a Unicorn in Under Two Years'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '07:36PM',\n",
       "  'Former AWS veteran Charlie Bell to head cybersecurity ops at Microsoft'],\n",
       " ['AMZN', 'Sep-15-21', '05:25PM', '10 Cheap Space Stocks Popular On Reddit'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '05:05PM',\n",
       "  'Checking In on Lemonade, Spotify, and Etsy'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '04:43PM',\n",
       "  '25 Largest ETFs by Assets Under Management'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '03:01PM',\n",
       "  'Tech Giants Used Loopholes to Duck Merger Reviews, FTC Says'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '02:49PM',\n",
       "  'Rivian For The Win: Electric Vehicle Maker Targets $8B IPO Windfall'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '02:42PM',\n",
       "  \"Goldman Sachs on Apple: Delta variant will make iPhone sales 'challenging'\"],\n",
       " ['AMZN', 'Sep-15-21', '01:51PM', 'When will Amazon stock skyrocket again?'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '01:27PM',\n",
       "  'Amazon reaches agreement with trade unions in Italy'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '12:50PM',\n",
       "  'Markets Stay Mixed as Goldman Sachs Fights Back Against Fintech Disruptors'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '12:41PM',\n",
       "  'Amazon Loss of Executive to Microsoft Sets Up Potential Clash'],\n",
       " ['AMZN', 'Sep-15-21', '12:33PM', '10 Cheap Small-Cap Stocks to Buy'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '11:55AM',\n",
       "  'BofA Identifies Tech Moonshots to Catch Next Apple, Amazon'],\n",
       " ['AMZN', 'Sep-15-21', '11:55AM', \"Amazon's New TVs Are No Threat to Roku\"],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '11:19AM',\n",
       "  'Ex-Google exec describes 4 top dangers of artificial intelligence'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '11:00AM',\n",
       "  \"3 Stocks You'll Be Glad You Bought at These Prices\"],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '10:46AM',\n",
       "  \"Is Kroger Stock A Buy Right Now? Here's What Earnings, Charts Show\"],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '10:38AM',\n",
       "  \"UBER's Chief Technology Officer Steps Down After Short Stint\"],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '10:30AM',\n",
       "  'Rivian produces electric pickup truck beating Tesla, Ford'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '10:15AM',\n",
       "  \"Is Kroger Stock A Buy Right Now? Here's What Earnings, Charts Show\"],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '10:05AM',\n",
       "  'Proceed With Caution When Considering These 5 Ultra-Popular Stocks'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '10:00AM',\n",
       "  'Could This Under-the-Radar AI Stock Help Boost Your Growth Portfolio?'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '09:54AM',\n",
       "  'This analyst says Uber, Netflix are the top tech stocks to buy right now'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '09:43AM',\n",
       "  'Microsoft Plans to Buy Back Up to $60 Billion in Stock'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '09:40AM',\n",
       "  '3 Top Chinese Stocks to Watch in September'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '09:24AM',\n",
       "  '10 Technology Stocks to Buy According to Mario Gabelli'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '08:45AM',\n",
       "  '3 E-Commerce Stocks That Have Killer Advantages'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '08:28AM',\n",
       "  \"Here's Why Home Depot Stock Could Make You Richer\"],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '07:00AM',\n",
       "  'This is the single largest danger of A.I. according to expert Kai-Fu Lee'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '07:00AM',\n",
       "  'Calavo Growers Appoints Amazon Executive Mariela Matute as CFO'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '06:22AM',\n",
       "  'Why Is Everyone Talking About Affirm Stock?'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '06:22AM',\n",
       "  '3 Stocks I Bought That Could Produce 10X Returns'],\n",
       " ['AMZN', 'Sep-15-21', '06:00AM', 'Influencers with Andy Serwer: Kai-Fu Lee'],\n",
       " ['AMZN',\n",
       "  'Sep-15-21',\n",
       "  '01:00AM',\n",
       "  'Should companies pay workers bonuses for turning up on time?'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '09:00PM',\n",
       "  'Amazon Brings Palm Swiping Tech to Concerts in Latest Entertainment Push'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '07:14PM',\n",
       "  'Check Out What Amazons Up To Now! Says BofA'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '07:12PM',\n",
       "  'Amazon Adding 125,000 Workers in U.S., Opening Dozens of Facilities'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '05:23PM',\n",
       "  'Uber Tech Chief Steps Down After Less Than a Year on the Job'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '04:04PM',\n",
       "  'Amazon Plans to Hire 125,000 Workers With Average Starting Pay at $18 an Hour'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '03:18PM',\n",
       "  'Amazon hires Twitter executive to tackle diversity challenges'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '12:20PM',\n",
       "  \"UPDATE 4-'Amazon won't change without a union': Canadian warehouse files for union vote\"],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '11:30AM',\n",
       "  'Amazon Aims To Hire 125,000 More Workers, Offering Them Average Hourly Pay Starting At $18'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '11:15AM',\n",
       "  'Up 70% This Month! Is Affirm Still a Buy Right Now?'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '11:05AM',\n",
       "  'Kroger Bets on Instacart Partnership in Grocery Delivery Square-Off With Amazon'],\n",
       " ['AMZN', 'Sep-14-21', '10:54AM', '3 ETFs Perfect to Grow Your IRA'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '10:50AM',\n",
       "  'Disney to release rest of 2021 slate exclusively in theaters'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '10:45AM',\n",
       "  'Amazons latest hiring spree, Steve Cohen investing in crypto, Google fined $177 million'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '10:44AM',\n",
       "  \"Here's what you need to know about Apple's iPhone event\"],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '10:43AM',\n",
       "  'Amazon Boosts Pay, Targets 125,000 Hires Amid Labor Shortage'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '10:37AM',\n",
       "  'TripAdvisor (TRIP) Partners Audible to Reach More Travelers'],\n",
       " ['AMZN', 'Sep-14-21', '10:18AM', '3 Disrupter Stocks I Love Right Now'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '10:00AM',\n",
       "  'Why Fading Fiscal Stimulus Is Less Harmful to eBay Than Amazon'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '09:23AM',\n",
       "  '3 Futuristic Stocks for a 5G, Cannabis, and Metaverse World'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '09:13AM',\n",
       "  '3 Robinhood Stocks to Buy and Hold Forever'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '08:59AM',\n",
       "  '5 Stocks That Could Turn $50,000 Into $1 Million by 2040'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '08:18AM',\n",
       "  \"Amazon technology will allow guests to enter Denver's Red Rocks Amphitheatre with a wave of the palm\"],\n",
       " ['AMZN', 'Sep-14-21', '07:55AM', '2 Beaten-Down Tech Stocks to Watch'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '07:19AM',\n",
       "  'The 1 FAANG Stock to Buy Hand Over Fist for the Second Half of 2021 (and Beyond)'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '07:00AM',\n",
       "  'Amazon Announces Plans to Hire Over 7,500 Employees in Several Cities and Towns Across Arizona'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '06:31AM',\n",
       "  'UPDATE 1-Amazon boosts hourly pay to over $18, to hire 125,000 workers'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '06:26AM',\n",
       "  'Amazon boosts hourly pay to over $18, to hire 125,000 workers'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '06:11AM',\n",
       "  'Amazon to hire 125,000 full- and part-time logistics employees'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '06:00AM',\n",
       "  'Amazon Announces Plans to Hire 125,000 Employees in Hundreds of Cities and Towns Across America'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '05:51AM',\n",
       "  '3 Nasdaq 100 Stocks Begging to Be Bought in September'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '05:16AM',\n",
       "  'South Korea Fines Google for Abusing Smartphone Dominance'],\n",
       " ['AMZN',\n",
       "  'Sep-14-21',\n",
       "  '05:04AM',\n",
       "  'Exclusive-Amazon hikes starting pay to $18 an hour as it hires for 125,000 more logistics jobs'],\n",
       " ['AMZN',\n",
       "  'Sep-13-21',\n",
       "  '05:55PM',\n",
       "  'Oracle Falls After Sales Miss Estimates on Cloud App Growth'],\n",
       " ['AMZN',\n",
       "  'Sep-13-21',\n",
       "  '04:00PM',\n",
       "  'Chipmaker And Electric Vehicle Stocks Set To Soar This Year'],\n",
       " ['AMZN', 'Sep-13-21', '02:45PM', 'Why Is Affirm Plunging on Monday?'],\n",
       " ['AMZN',\n",
       "  'Sep-13-21',\n",
       "  '02:01PM',\n",
       "  'Amazon D.C. Antitrust Suit Grows to Include Wholesale Goods'],\n",
       " ['AMZN',\n",
       "  'Sep-13-21',\n",
       "  '12:51PM',\n",
       "  'D.C. attorney general broadens Amazon lawsuit'],\n",
       " ['AMZN',\n",
       "  'Sep-13-21',\n",
       "  '12:34PM',\n",
       "  'BNPL Providers Not Charging Late Fees May Face Consequences'],\n",
       " ['AMZN',\n",
       "  'Sep-13-21',\n",
       "  '11:56AM',\n",
       "  'Algorithms Are Great But People Dictate Success For Big-And-Bulky Delivery'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '11:50PM',\n",
       "  'Teslas Elon Musk praises Chinese auto makers, vows to ensure cars data security: reports'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '11:26PM',\n",
       "  'Dow Jones Futures: Market Rally Resilient, Tesla Strong Amid ARK Sales; 5 Stocks Flash Buy Signals'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '10:29PM',\n",
       "  'UPDATE 2-Tesla to work with global regulators on data security -Musk'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '10:26PM',\n",
       "  'Tesla to work with global regulators on data security -Musk'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '08:07PM',\n",
       "  '5 Best Chinese Stocks To Buy And Watch As Beijing Crackdowns Continue'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '06:42PM',\n",
       "  'GM Gets a Jolt From Bolt. Whats at Stake With the EV Recall.'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '05:11PM',\n",
       "  'Why Is Tesla Mad About New EV Tax Credits?'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '04:27PM',\n",
       "  \"Lucid is a combo of 'Tesla and Ferrari': BofA analyst\"],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '04:13PM',\n",
       "  'Cathie Wood Likes Tesla. But Her ARK Funds Keep Selling the Stock.'],\n",
       " ['TSLA', 'Sep-16-21', '02:03PM', 'Why Lucid Group Stock Is Higher Today'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '01:52PM',\n",
       "  'Fords Lightning pickup could make electric vehicles popular with all consumers, not just the green ones'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '01:06PM',\n",
       "  'US STOCKS-Wall Street slips as tech, energy stocks drop'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '12:44PM',\n",
       "  'Lucid Motors rebounds on Bank of America bullish outlook'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '12:17PM',\n",
       "  'Dow Jones Falls As Jobless Claims Rise, Retail Sales Jump; Apple, Tesla Slide'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '12:11PM',\n",
       "  \"'Space X is by far the most diversified of all of these space companies:' CEO of space ETF\"],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '12:02PM',\n",
       "  'Is Lucid Motors Stock A Buy Right As Lucid Air Gets EPA Rating Of 520 Miles Per Charge?'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '11:29AM',\n",
       "  'How Facebook plans to earn peoples trust with its Novi digital wallet'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '11:04AM',\n",
       "  'Cathie Wood unloads $62 million of Tesla shares'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '10:40AM',\n",
       "  'SpaceX launches all-civilian crew into space'],\n",
       " ['TSLA', 'Sep-16-21', '10:38AM', '10 New Penny Stocks Redditors are Buying'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '09:58AM',\n",
       "  'House Democrats plan EV tax credits of up to $12,500, as Republicans, Tesla, Toyota voice objections'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '08:14AM',\n",
       "  'Tesla Opens Store on Tribal Land in New Mexico, Avoids Dealer Rule'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '07:12AM',\n",
       "  'Instead of Buying Dogecoin, Invest in These 3 Companies That Are Bullish on Blockchain Technology'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '06:35AM',\n",
       "  'Lucid Gains as Air Dream Edition Range Gets Longest-range EV Tag from EPA'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '06:00AM',\n",
       "  'Metaverse raises scary question on surveillance of users: Kai-Fu Lee'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '05:34AM',\n",
       "  \"Cathie Wood's Ark Dumps $62 Million More of Tesla Shares\"],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '03:57AM',\n",
       "  'Moderna, Electronic Arts Rise Premarket; Tesla, Beyond Meat Fall'],\n",
       " ['TSLA',\n",
       "  'Sep-16-21',\n",
       "  '02:12AM',\n",
       "  'Cathie Wood Keeps Selling Tesla, Unloading $62 Million of Shares'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '06:01PM',\n",
       "  'Tesla builds first store on tribal land, dodging state car laws'],\n",
       " ['TSLA', 'Sep-15-21', '05:25PM', '10 Cheap Space Stocks Popular On Reddit'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '04:25PM',\n",
       "  'Dow Jones Rises As Nasdaq Rallies; Tesla Gains Despite Losing This Race; BioNTech Gets Vaccine Boost'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '04:09PM',\n",
       "  'Rivian Beats Tesla, GM With First Electric Pickup; Nikola Set To Begin Semi Production'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '01:54PM',\n",
       "  'Theres a $25,000 EV Coming, But It Isnt From Tesla'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '12:49PM',\n",
       "  'Rivian aims to raise as much as $8 bln in IPO -sources'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '12:46PM',\n",
       "  'U.S. needs to do these 3 things to ensure majority of new cars are electric by 2030: Michigan congresswoman'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '12:21PM',\n",
       "  '10 Penny Stocks with Upcoming Growth Catalysts'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '11:15AM',\n",
       "  'Dow Jones Advances As Apple Falls To Key Level; Microsoft Jumps On Buyback Plan'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '10:30AM',\n",
       "  'Rivian produces electric pickup truck beating Tesla, Ford'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '09:54AM',\n",
       "  'Xpeng launches P5 Sedan with starting price around $24.5K'],\n",
       " ['TSLA', 'Sep-15-21', '08:59AM', 'Cathie Wood Is Selling These 10 Stocks'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '07:00AM',\n",
       "  'This is the single largest danger of A.I. according to expert Kai-Fu Lee'],\n",
       " ['TSLA',\n",
       "  'Sep-15-21',\n",
       "  '06:02AM',\n",
       "  'Cathie Wood Sells $66 Million of Tesla Shares, Adds Robinhood'],\n",
       " ['TSLA', 'Sep-15-21', '06:00AM', 'Influencers with Andy Serwer: Kai-Fu Lee'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '10:24PM',\n",
       "  'UPDATE 1-Amazon-backed startup Rivian starts production of electric pickup truck'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '05:45PM',\n",
       "  'Tesla (TSLA) Gains As Market Dips: What You Should Know'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '05:05PM',\n",
       "  'Amazon-backed startup Rivian starts production of electric pickup truck'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '04:59PM',\n",
       "  'Amazon-backed startup Rivian starts production of electric pick-up'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '04:53PM',\n",
       "  'Here are 5 ways to profit from the crypto crash without buying volatile coins'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '04:13PM',\n",
       "  'Ark Drops Out of Top 10 ETF Issuers as Shiny Lure Fades'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '04:05PM',\n",
       "  'UPDATE 1-Redwood, led by Tesla co-founder, to build battery materials in U.S.'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '11:10AM',\n",
       "  'Analyzing Tesla, Inc. (TSLA): Future Growth Catalysts, Hedge Fund Sentiment and Analyst Ratings'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '11:05AM',\n",
       "  'Is Li Auto Stock A Buy? Shares Near Critical Level After August Sales Jump 248%'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '11:04AM',\n",
       "  'Dow Jones Slides As Inflation Cools, But Still High; Apple Climbs Ahead Of IPhone 13 Debut'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '10:57AM',\n",
       "  'U.S. asks 12 automakers for assistance in Tesla probe'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '10:02AM',\n",
       "  'UPDATE 1-China develops machines that can track data sent abroad by cars'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '09:44AM',\n",
       "  'Morning Brief: U.S. and China relations take center stage'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '09:34AM',\n",
       "  'Hurricane Ida, chip shortage hurting car dealers'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '09:02AM',\n",
       "  'China develops machines that can track data sent abroad by cars'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '08:56AM',\n",
       "  'China develops machines to track data sent abroad by cars'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '08:35AM',\n",
       "  'A Tesla Co-Founder Aims To Build an Entire U.S. Battery Industry'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '08:08AM',\n",
       "  'General Motors (GM) Boosts AV Capabilities on Oculii Investment'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '07:54AM',\n",
       "  'Dow Jones Futures Reverse Lower As Apple iPhone 13 Set To Debut'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '07:35AM',\n",
       "  'Why Is Everyone Talking About Lucid Group Stock?'],\n",
       " ['TSLA',\n",
       "  'Sep-14-21',\n",
       "  '07:00AM',\n",
       "  'Teenager starts non-profit to teach kids how to invest'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '07:45PM',\n",
       "  'UPDATE 1-Tesla, Toyota spar with Ford, UAW over EV tax bill'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '07:35PM',\n",
       "  'Tesla (TSLA) CEO Criticizes Electric Vehicle Bill'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '07:30PM',\n",
       "  'Gasoline Or Electric: Which Is The Best Car For A Road Trip?'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '04:14PM',\n",
       "  'EV Stocks Face New Policy Moves From Beijing To Washington'],\n",
       " ['TSLA', 'Sep-13-21', '03:39PM', 'Top Electric Car Stocks for Q4 2021'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '03:05PM',\n",
       "  'Is Ford Stock A Buy Now? Automaker Exits India Amid August Sales Slump'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '02:29PM',\n",
       "  'Cinema stocks jump, Chinas crowded EV space, crypto stocks slide after Walmart-Litecoin hoax'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '01:00PM',\n",
       "  'General Motors Invests In Autonomous Car Radar Company: Reuters'],\n",
       " ['TSLA', 'Sep-13-21', '12:25PM', 'Why Tesla Stock Fell on Monday'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '11:40AM',\n",
       "  'HOG vs. TSLA: Which Stock Is the Better Value Option?'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '11:24AM',\n",
       "  'Tesla (TSLA) Option Traders Positioned for a Move Lower'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '11:22AM',\n",
       "  'Dow Jones Rallies 300 Points As Apple Rebounds, But Tesla Sells Off; Four Top Growth Stocks To Buy And Watch'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '10:34AM',\n",
       "  \"EV Roundup: TM's $13.5B Battery War Chest, NIO's $2B Share Offering & More\"],\n",
       " ['TSLA', 'Sep-13-21', '08:35AM', '3 Stocks to Avoid This Week'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '08:14AM',\n",
       "  \"Dow Jones Futures Rise After Apple Led 'Epic' Market Rally Retreat; Covid Cases Fall Sharply\"],\n",
       " ['TSLA', 'Sep-13-21', '08:11AM', 'Is Tesla a Buy Now?'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '08:04AM',\n",
       "  'Tesla (TSLA) Raises Model Y Performance Car Price in China'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '07:18AM',\n",
       "  'Savvy stock traders use these 2 insider tips to know when to buy and sell'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '07:15AM',\n",
       "  'GM invests in Oculii, radar software maker for self-driving cars'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '06:02AM',\n",
       "  'Federal EV Incentives To Give Tesla, General Motors a Boost. America Is Catching Up.'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '06:00AM',\n",
       "  'GM invests in Oculii, radar software maker for self-driving cars'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '05:10AM',\n",
       "  'Suddenly everyone thinks the stock market is going to plunge: Morning Brief'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '04:24AM',\n",
       "  'Premarket Movers Monday - Apple, Virgin Galactic, Airbnb, Tesla'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '12:06AM',\n",
       "  'GM digs in with LG Corp to speed a fix for Bolt battery fires'],\n",
       " ['TSLA',\n",
       "  'Sep-13-21',\n",
       "  '12:00AM',\n",
       "  'FOCUS-GM digs in with LG Corp to speed a fix for Bolt battery fires'],\n",
       " ['TSLA',\n",
       "  'Sep-12-21',\n",
       "  '12:19PM',\n",
       "  'Federal EV Incentives To Give Tesla, General Motors a Boost. America Is Catching Up.'],\n",
       " ['TSLA',\n",
       "  'Sep-12-21',\n",
       "  '08:45AM',\n",
       "  \"Why Tesla's Surging Chinese Vehicle Sales Are Electrifying for Investors\"],\n",
       " ['TSLA',\n",
       "  'Sep-11-21',\n",
       "  '08:28PM',\n",
       "  'UPDATE 1-Toyota, Honda oppose U.S. House electric vehicle tax plan'],\n",
       " ['TSLA', 'Sep-11-21', '09:08AM', '3 Top Robinhood Stocks Wall Street Loves'],\n",
       " ['TSLA',\n",
       "  'Sep-11-21',\n",
       "  '04:00AM',\n",
       "  \"EV Checkpoint: Cramer Says Ford Hired Apple Exec 'To Defeat Musk'\"],\n",
       " ['TSLA',\n",
       "  'Sep-10-21',\n",
       "  '04:46PM',\n",
       "  'Replay: Wejo CEO & VOSO CEO in Fireside Chat'],\n",
       " ['TSLA',\n",
       "  'Sep-10-21',\n",
       "  '04:39PM',\n",
       "  'Stock Market Rally Pulls Back; Lululemon, Affirm, Tesla, Coinbase In Focus: Weekly Review'],\n",
       " ['TSLA',\n",
       "  'Sep-10-21',\n",
       "  '04:13PM',\n",
       "  \"Cathie Wood's Ark ETFs Sell\\xa0$139 Million Worth of Tesla Stock\"],\n",
       " ['TSLA',\n",
       "  'Sep-10-21',\n",
       "  '01:00PM',\n",
       "  \"ETFs to Tap on Rivian's High-Profile IPO Move\"],\n",
       " ['TSLA',\n",
       "  'Sep-10-21',\n",
       "  '10:58AM',\n",
       "  'Dow Jones Falls 100 Points; Biden, Xi Talk; Affirm Skyrockets On Earnings'],\n",
       " ['TSLA',\n",
       "  'Sep-10-21',\n",
       "  '10:21AM',\n",
       "  \"Is Nio Stock A Buy As China's Tesla Plans 3 New EVs In 2022?\"],\n",
       " ['GOOG',\n",
       "  'Sep-17-21',\n",
       "  '02:08AM',\n",
       "  'Google, Apple remove Navalny app from stores as Russian elections begin'],\n",
       " ['GOOG',\n",
       "  'Sep-17-21',\n",
       "  '02:03AM',\n",
       "  'Google, Apple remove Navalny app from stores as Russian elections begin'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '08:58PM',\n",
       "  'These Are The Best Robinhood Stocks To Buy Or Watch Now'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '05:45PM',\n",
       "  'Alphabet (GOOGL) Dips More Than Broader Markets: What You Should Know'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '04:39PM',\n",
       "  '10 Tech Stocks to Invest in Today According to Thomas E. Claugus GMT Capital'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '04:01PM',\n",
       "  'FTC, Biden Antitrust Enforcement Push Takes On Amazon, Google  And The Supreme Court'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '03:00PM',\n",
       "  'This map shows the most-searched pumpkin spice foods in every state'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '02:06PM',\n",
       "  'Altcoins Like Bitcoin Cash and Litecoin Were Thrust Into the Limelight by AMC Today'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '01:20PM',\n",
       "  'Microsoft (MSFT) Board Approves $60B Share Repurchase Program'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '12:25PM',\n",
       "  'How long might it take to resolve the Epic-Apple case? Expect a legal marathon'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '12:17PM',\n",
       "  'S&P 500 Closes Down, but Above Lows Despite Fresh Worries of Fed Tightening'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '11:29AM',\n",
       "  'How Facebook plans to earn peoples trust with its Novi digital wallet'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '11:21AM',\n",
       "  'Russia Targets Google, Apple in Crackdown Before Elections'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '10:49AM',\n",
       "  'S&P 500 Off Session Lows, but Surprise Rise in Retail Sales Stokes Fed Fears'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '10:31AM',\n",
       "  'Top 10 Stock Picks of Ryan Fricks Dorsal Capital: Facebook, Snap and More'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '10:25AM',\n",
       "  'Is Google Stock A Buy? Internet Search Giant Tops Among FANG Stocks In 2021'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '10:20AM',\n",
       "  'Is Snowflake Stock A Buy? Data Analytics Specialist Rides Cloud Computing Wave'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '10:15AM',\n",
       "  'Is Salesforce Stock A Buy? Slack Integration Roadmap Expected At Dreamforce'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '09:39AM',\n",
       "  'Metaverse raises scary question on surveillance of users, ex-Google exec says'],\n",
       " ['GOOG', 'Sep-16-21', '09:22AM', 'Is Roku Stock a Buy?'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '07:15AM',\n",
       "  \"3 Long-Term Investments You'll Thank Yourself for Later\"],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '06:00AM',\n",
       "  'Metaverse raises scary question on surveillance of users: Kai-Fu Lee'],\n",
       " ['GOOG',\n",
       "  'Sep-16-21',\n",
       "  '06:00AM',\n",
       "  'Byjus Buys Coding Site Tynker for $200 Million to Grow in U.S.'],\n",
       " ['GOOG', 'Sep-16-21', '05:20AM', 'Bull of the Day: The Trade Desk (TTD)'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '10:16PM',\n",
       "  'Forget fourth stimulus  these stocks offer income checks growing as fast as 11%'],\n",
       " ['GOOG', 'Sep-15-21', '05:25PM', '10 Cheap Space Stocks Popular On Reddit'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '04:43PM',\n",
       "  '25 Largest ETFs by Assets Under Management'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '04:21PM',\n",
       "  'Startup aims to help busy moms with personal assistant service'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '03:01PM',\n",
       "  'Tech Giants Used Loopholes to Duck Merger Reviews, FTC Says'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '02:42PM',\n",
       "  \"Goldman Sachs on Apple: Delta variant will make iPhone sales 'challenging'\"],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '02:08PM',\n",
       "  'Apple is relying on the iPhone 13s new cameras to power record sales'],\n",
       " ['GOOG', 'Sep-15-21', '01:51PM', 'When will Amazon stock skyrocket again?'],\n",
       " ['GOOG', 'Sep-15-21', '12:33PM', '10 Cheap Small-Cap Stocks to Buy'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '12:33PM',\n",
       "  'S&P 500 Snaps Losing Streak as Energy Boost Coaxes Bulls From Hiding'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '12:25PM',\n",
       "  'Wells Fargo picks Microsoft, Google as cloud service providers'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '11:19AM',\n",
       "  'Ex-Google exec describes 4 top dangers of artificial intelligence'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '09:54AM',\n",
       "  'This analyst says Uber, Netflix are the top tech stocks to buy right now'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '09:43AM',\n",
       "  'Microsoft Plans to Buy Back Up to $60 Billion in Stock'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '07:22AM',\n",
       "  'Can This Growth Stock Recover From a Huge Price Drop?'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '07:05AM',\n",
       "  'Facebook vs. Alphabet Stock: Which Tech Stock Is the Better Buy?'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '07:00AM',\n",
       "  'This is the single largest danger of A.I. according to expert Kai-Fu Lee'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '06:07AM',\n",
       "  \"Big Tech's little mergers draw more U.S. antitrust scrutiny\"],\n",
       " ['GOOG', 'Sep-15-21', '06:00AM', 'Influencers with Andy Serwer: Kai-Fu Lee'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '06:00AM',\n",
       "  \"FTC staff to present findings on Big Tech's smaller acquisitions\"],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '02:12AM',\n",
       "  'Google says it offers more than $10 billion in consumer benefits in S.Korea'],\n",
       " ['GOOG',\n",
       "  'Sep-15-21',\n",
       "  '02:06AM',\n",
       "  'Google says it offers more than $10 bln in consumer benefits in S.Korea'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '10:26PM',\n",
       "  'Buffett-Backed Indian Fintech Giant Faces Challenges as IPO Nears'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '08:00PM',\n",
       "  'Founder Says Huawei More United Than Ever After U.S. Blacklist'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '02:23PM',\n",
       "  'Apple unveils $699 iPhone 13 and $999 iPhone 13 Pro'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '01:39PM',\n",
       "  'Apple debuts Apple Watch Series 7 with more durable design, bigger screen'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '11:30AM',\n",
       "  \"Facebook's Path Into Wearables Will Be an Uphill Climb\"],\n",
       " ['GOOG', 'Sep-14-21', '10:54AM', '3 ETFs Perfect to Grow Your IRA'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '10:45AM',\n",
       "  'Amazons latest hiring spree, Steve Cohen investing in crypto, Google fined $177 million'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '10:44AM',\n",
       "  \"Here's what you need to know about Apple's iPhone event\"],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '10:33AM',\n",
       "  \"Chip Dip Slip? Not So Much for Alphabet's (GOOG) Google\"],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '10:23AM',\n",
       "  'Square (SQ) Ups Touch-Free Payment Efforts With Cash App Pay'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '10:15AM',\n",
       "  'Michael Burry is Loading Up on These 9 Stocks'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '08:48AM',\n",
       "  '5 Stocks to Watch as Cloud-Based Platform Service Demand Rises'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '08:25AM',\n",
       "  'Google Fined Over Android Rules in Second South Korea Setback. What to Know.'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '08:01AM',\n",
       "  'Google Fined Over Android Rules in Second South Korea Setback. What to Know.'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '08:00AM',\n",
       "  'Apples split decision in Epic case resolves lawmakers, regulators to push harder for antitrust law'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '07:19AM',\n",
       "  'The 1 FAANG Stock to Buy Hand Over Fist for the Second Half of 2021 (and Beyond)'],\n",
       " ['GOOG',\n",
       "  'Sep-14-21',\n",
       "  '05:16AM',\n",
       "  'South Korea Fines Google for Abusing Smartphone Dominance'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '11:43PM',\n",
       "  'South Korea Fines Google for Abusing Android Dominance'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '11:24PM',\n",
       "  'UPDATE 3-S.Korea fines Google $177 mln for blocking Android customisation'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '11:03PM',\n",
       "  'S.Korea fines Google $177 million for blocking Android customisation'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '05:45PM',\n",
       "  'Alphabet Inc. (GOOG) Outpaces Stock Market Gains: What You Should Know'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '04:28PM',\n",
       "  'Oracle Falls After Sales Miss Estimates on Cloud App Growth'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '02:52PM',\n",
       "  'Top Stocks to Buy Today According to Rob Koehns Ivy Lane Capital'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '12:54PM',\n",
       "  'Bannon-Linked Media Firm Is Part of $539 Million SEC Case'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '11:46AM',\n",
       "  'Apple (AAPL) App Store Prospects Clouded by Epic Games Ruling'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '11:13AM',\n",
       "  \"Tech Market In Focus After Big Friday Slide From Apple, Alphabet Following Judge's Decision\"],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '09:50AM',\n",
       "  '4 Stocks to Gain From the Unbridled Popularity of Smartwatches'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '09:44AM',\n",
       "  '10 Best Stocks to Buy According to Ric Dillons Diamond Hill Capital'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '09:32AM',\n",
       "  \"Morgan Stanley sees a potential 10% market correction happening soon -- here's why\"],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '08:14AM',\n",
       "  \"Dow Jones Futures Rise After Apple Led 'Epic' Market Rally Retreat; Covid Cases Fall Sharply\"],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '08:00AM',\n",
       "  'Investors Score Big On Five Companies Making $1 Billion A Day'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '06:00AM',\n",
       "  'Meet The Woman Behind Googles Multi-Million Dollar Partnerships With Black Founders Around The Globe'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '05:10AM',\n",
       "  'Suddenly everyone thinks the stock market is going to plunge: Morning Brief'],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '03:44AM',\n",
       "  \"Sorrell's S4 Capital ups profit outlook as losses widen\"],\n",
       " ['GOOG',\n",
       "  'Sep-13-21',\n",
       "  '02:30AM',\n",
       "  '[video]5 Thoughts on the Apple/Epic Ruling and Its Potential Fallout'],\n",
       " ['GOOG',\n",
       "  'Sep-12-21',\n",
       "  '03:26PM',\n",
       "  'Epic Files Appeal After Loss to Apple in App Store Case'],\n",
       " ['GOOG',\n",
       "  'Sep-12-21',\n",
       "  '05:00AM',\n",
       "  \"Tech Stocks Roundup: Google is the 'Cheapest of FAANG'\"],\n",
       " ['GOOG',\n",
       "  'Sep-11-21',\n",
       "  '06:05PM',\n",
       "  '2 Smart Stocks With the Potential for Fivefold Growth'],\n",
       " ['GOOG',\n",
       "  'Sep-11-21',\n",
       "  '08:30AM',\n",
       "  'Apple Ruling Poses Hurdles for Bidens Vow to Tackle Tech Giants'],\n",
       " ['GOOG',\n",
       "  'Sep-11-21',\n",
       "  '08:19AM',\n",
       "  '7 New Stocks to Invest In According to Michael Burry'],\n",
       " ['GOOG',\n",
       "  'Sep-11-21',\n",
       "  '07:45AM',\n",
       "  'Sky-High Faang Stocks Were Never Anything But Screaming Bargains'],\n",
       " ['GOOG',\n",
       "  'Sep-11-21',\n",
       "  '06:23AM',\n",
       "  '5 Leading Growth Stocks to Buy in 2021 and Beyond'],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '08:30PM',\n",
       "  \"Analysis-Epic's narrow win in App Store case toughens fight against Google Play rules\"],\n",
       " ['GOOG', 'Sep-10-21', '06:32PM', 'Why Apple Stock Dropped Today'],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '05:45PM',\n",
       "  'Alphabet (GOOGL) Dips More Than Broader Markets: What You Should Know'],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '05:43PM',\n",
       "  'Ruling in Epic-Apple case could hit core of App Store, but Apple escapes monopolist label'],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '04:13PM',\n",
       "  'Apples App Store Grip Loosened as Judge Raps Pricing Power'],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '03:16PM',\n",
       "  'Google Could Have Violated Labor Laws: NYT'],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '02:51PM',\n",
       "  'Apple cant force developers to use its in-app payment system, federal judge rules'],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '02:24PM',\n",
       "  'Why Elastic Is Up, Why Fastly Has Hit a Wall, and Can Lemonade Actually Disrupt Insurance?'],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '01:13PM',\n",
       "  'Will FAANG stocks get routed because of the Federal Reserve?'],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '12:10PM',\n",
       "  'Kremlin internet crackdown causing major outages as election looms'],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '12:07PM',\n",
       "  \"Epic v. Apple ruling: Judge finds Apple's App Store restrictions violate antitrust law\"],\n",
       " ['GOOG',\n",
       "  'Sep-10-21',\n",
       "  '11:31AM',\n",
       "  'Yandex (YNDX) to Begin Testing Autonomous Vehicles in Moscow']]"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "parsed_news = []\n",
    "for file_name, news_table in news_tables.items():\n",
    "    for x in news_table.findAll('tr'):\n",
    "        text = x.a.get_text()\n",
    "        date_scrape = x.td.text.split()\n",
    "        if len(date_scrape) == 1:\n",
    "            time = date_scrape[0]\n",
    "        else:\n",
    "            date = date_scrape[0]\n",
    "            time = date_scrape[1]\n",
    "        ticker = file_name.split('_')[0]\n",
    "        parsed_news.append([ticker,date,time,text])\n",
    "parsed_news"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "1eeea14a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ticker</th>\n",
       "      <th>date</th>\n",
       "      <th>time</th>\n",
       "      <th>headline</th>\n",
       "      <th>neg</th>\n",
       "      <th>neu</th>\n",
       "      <th>pos</th>\n",
       "      <th>compound</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>AMZN</td>\n",
       "      <td>2021-09-16</td>\n",
       "      <td>10:30PM</td>\n",
       "      <td>Amazon, Microsoft Swoop In on $24 Billion Indi...</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.841</td>\n",
       "      <td>0.159</td>\n",
       "      <td>0.1779</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>AMZN</td>\n",
       "      <td>2021-09-16</td>\n",
       "      <td>05:45PM</td>\n",
       "      <td>Amazon (AMZN) Gains As Market Dips: What You S...</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.661</td>\n",
       "      <td>0.339</td>\n",
       "      <td>0.4767</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>AMZN</td>\n",
       "      <td>2021-09-16</td>\n",
       "      <td>04:39PM</td>\n",
       "      <td>10 Tech Stocks to Invest in Today According to...</td>\n",
       "      <td>0.00</td>\n",
       "      <td>1.000</td>\n",
       "      <td>0.000</td>\n",
       "      <td>0.0000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>AMZN</td>\n",
       "      <td>2021-09-16</td>\n",
       "      <td>04:01PM</td>\n",
       "      <td>FTC, Biden Antitrust Enforcement Push Takes On...</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.675</td>\n",
       "      <td>0.325</td>\n",
       "      <td>0.6486</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>AMZN</td>\n",
       "      <td>2021-09-16</td>\n",
       "      <td>01:49PM</td>\n",
       "      <td>Co-op criticised after announcing new partners...</td>\n",
       "      <td>0.17</td>\n",
       "      <td>0.727</td>\n",
       "      <td>0.103</td>\n",
       "      <td>-0.2732</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  ticker        date     time  \\\n",
       "0   AMZN  2021-09-16  10:30PM   \n",
       "1   AMZN  2021-09-16  05:45PM   \n",
       "2   AMZN  2021-09-16  04:39PM   \n",
       "3   AMZN  2021-09-16  04:01PM   \n",
       "4   AMZN  2021-09-16  01:49PM   \n",
       "\n",
       "                                            headline   neg    neu    pos  \\\n",
       "0  Amazon, Microsoft Swoop In on $24 Billion Indi...  0.00  0.841  0.159   \n",
       "1  Amazon (AMZN) Gains As Market Dips: What You S...  0.00  0.661  0.339   \n",
       "2  10 Tech Stocks to Invest in Today According to...  0.00  1.000  0.000   \n",
       "3  FTC, Biden Antitrust Enforcement Push Takes On...  0.00  0.675  0.325   \n",
       "4  Co-op criticised after announcing new partners...  0.17  0.727  0.103   \n",
       "\n",
       "   compound  \n",
       "0    0.1779  \n",
       "1    0.4767  \n",
       "2    0.0000  \n",
       "3    0.6486  \n",
       "4   -0.2732  "
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "vader = SentimentIntensityAnalyzer()\n",
    "\n",
    "columns = ['ticker','date','time','headline']\n",
    "\n",
    "parsed_and_scored_news = pd.DataFrame(parsed_news, columns = columns)\n",
    "\n",
    "scores = parsed_and_scored_news['headline'].apply(vader.polarity_scores).tolist()\n",
    "\n",
    "scores_df = pd.DataFrame(scores)\n",
    "\n",
    "parsed_and_scored_news = parsed_and_scored_news.join(scores_df, rsuffix = '_right')\n",
    "\n",
    "parsed_and_scored_news['date'] = pd.to_datetime(parsed_and_scored_news.date).dt.date\n",
    "\n",
    "parsed_and_scored_news.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "0259c398",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlsAAAGmCAYAAABLIUErAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAoq0lEQVR4nO3dfXQU9b3H8c8mEQJEHjY8g08EEIsIhvDQgDxosAiFxFouVzmt3iD3iqINF0UND0crIALCvRUUSiNwxSpYjkFqpRJ84AAVQi0F2lKIUWtIaGg2CYaYSLJ7//C4NZkfQrr5Mbvk/TrHc7Izszvf/RDl48zsrCcQCAQEAAAAK6LcHgAAAOBSRtkCAACwiLIFAABgEWULAADAIsoWAACARZQtAAAAiyhbAAAAFsW4PcC3KSwsdHsEAACA8+rates513FkCwAAwCLKFgAAgEWULQAAAIvC+potAAAQHgKBgKqqquT3++XxeNwexxWBQEBRUVGKjY1tUAaULQAAcF5VVVW67LLLFBPTtKtDTU2Nqqqq1KJFiwt+DqcRAQDAefn9/iZftCQpJiZGfr+/Qc+hbAEAgPNqqqcOTRqaBWULAABcdOXl5Vq/fr0k6eTJk5o2bdq3bj9kyBD5fL6LMFnjo2wBAICL7vTp0/q///s/SVLnzp21du1aK/upqamx8roNwclXAABw0S1atEiffvqpxowZo2uuuUZ5eXl65513VFtbq4ULF+q9995TVFSU7rrrLqWnpwef98UXX2jatGm67bbbdPvtt2vu3Ln661//qrNnz2rWrFn63ve+p02bNumtt97SmTNn5Pf7tWXLFhffKWULAAC4IDMzU3/961+1Y8cOffbZZ7r77rslSRs3btRnn32mt99+WzExMSotLQ0+58yZM5o+fbp++MMfatKkSXr66ac1bNgwLV++XOXl5Ro/frxuuukmSdLhw4eVk5Ojdu3aufL+vomyBQAAwsbu3bv1ox/9KPjJx2+Wpf/4j//Q/fffrx/84AeSpF27dmnHjh1avXq1JKm6ulonTpyQJI0YMSIsipZE2QIumm2byi542wmT21qbAwAi1aBBg/Tuu+/q9ttvl8fjUSAQ0M9//nP17NmzznYffvihWrZs6dKUTo1ygfzBgwf1k5/8RA8++KCys7Md699++23NmjVLjzzyiObNm6eCgoLG2C0AAIhQrVq1UkVFhWP5TTfdpJdeeil4Yfs3TyM+8sgjatu2rTIzMyVJI0eO1Lp16xQIBCRJR44cuQiTN1zIZcvv9ysrK0uZmZlasWKF9uzZ4yhTw4cP17PPPqulS5cqNTVVGzZsCHW3AAAggnm9Xg0aNEg333yznnrqqeDyu+66S926dVNKSopSUlIcB3F++tOfqqqqSgsWLFBGRobOnj2rlJQUjR49WkuWLLnI7+LCeAJf18F/0bFjx/Taa69pzpw5kqTXX39dknT77bcbt9+9e7d27doVbKXfprCwMJTRgLDCaUQAkayysjKsTs25yZRF165dz7l9yNds+Xw+xcfHBx/Hx8fr+PHjju22b9+uN998UzU1NZo/f77xtXJycpSTkyNJWrx4caijAQAAuO6iXSA/duxYjR07Vrt379aWLVs0Y8YMxzZfHzIEAAC4VIR8zZbX61VJSUnwcUlJibxe7zm3T05OVm5ubqi7BQAAiAghl62EhAQVFRWpuLhYNTU12rt3r5KSkupsU1RUFPz5ww8/VJcuXULdLQAAQEQI+TRidHS00tPTtXDhQvn9fo0ePVpXXHGFNm3apISEBCUlJWn79u06fPiwoqOjFRcXpwceeKAxZgcAAAh7IX8a0SY+jYhLCZ9GBBDJ+DTiPzX004iNclNTAACAi2X79u3q1q2b8vLyJEmfffaZunXrpmeeeSa4jc/n01VXXRW8NdVdd92lMWPGBP9JTEzU97//fUlSRkaGBg4cqOrq6uBzhwwZ0mjz8nU9OK/Ul482aPutU/pYmgQAEC5qp01s1NeLXvvGBW+bnZ2twYMHKzs7Ww8//LAk6corr9TOnTv16KOPSpK2bdum3r17B5/zy1/+MvhzZWWlxo4dq9mzZweXRUVF6dVXXw1+IXZj4sgWAACIGGfOnFFubq6WLVumrVu3Bpe3aNFCvXr10h//+EdJX5WtCRMmGF9j/vz5uvnmmzVixIjgsnvvvVdr164Nfk1QY6JsAQCAiPHb3/5Wo0aNUkJCgtq1a6dDhw4F16Wmpmrr1q06ceKEoqKi1KlTJ8fzf/Ob3+iPf/yjHn/88TrLu3XrpsGDB2vLli2NPjNlCwAARIzs7GylpqZK+qpcffO7E0eNGqVdu3bpjTfe0MSJztOcRUVFmj9/vlatWqXmzZs71s+YMUMvvPCC/H5/o87MNVsAACAilJaWas+ePTp69Kg8Ho9qa2vl8Xh0zz33SJKaNWumG264QWvWrNG7776rt99+O/jcQCCgjIwMzZgxo861XN/Uo0cP9e3bV9u2bWvUuSlbAAAgIrz55pu64447tGTJkuCyO+64o86tov7rv/5LQ4cOVbt27eo8d/Xq1WrevHmwmJ3LQw89pB//+MeNOjdlCwAARITs7GzHjdHHjRunlStXBh9fe+21uvbaax3PXbJkibp06aIxY8YEl7Vp00a/+tWv6mx37bXXql+/fjp8+HCjzc1NTXFe3PqhcXBTUwCRjJua/hM3NQUAAAgjlC0AAACLKFsAAAAWUbYAAAAsomwBAABYRNkCAACwiLIFAAAixqlTp/TAAw/ou9/9rsaOHasJEyborbfekiTt379f48eP14gRIzRixAht3LixznM3btwYXDd+/Hjt378/uK6mpkZPP/20hg0bpjFjxmjMmDH63//930aZmZuaAgCABmvoPRjP50Lu0RgIBJSenq5JkyZp1apVkqSCggK9/fbbKi4u1gMPPKAXX3xR/fr1k8/n01133aXOnTsrJSVFO3bs0MaNG5WdnS2v16vDhw8rPT1db775pjp27KglS5aouLhYO3fuVGxsrCoqKrRmzZpGeW8c2QIAABFh9+7datasWZ2v0+nevbvS09O1fv16/du//Zv69esnSfJ6vZozZ06wlD3//POaO3euvF6vJKlfv36aNGmS1q9fry+++EIvv/yyFixYoNjYWElSXFycZs2a1ShzU7YAAEBEOHbsmK6//vpzrrvhhhvqLOvfv7+OHTt23vUff/yxunXrpri4OCtzU7YAAEBEyszMVEpKisaNG9eor7tp0yaNGTNGSUlJOnHiRMivR9kCAAARoXfv3jpy5Ejw8aJFi7R582aVlJSoV69eOnToUJ3tDx06pN69e0vSt66/5pprdOLECVVUVEiSJk+erB07dqh169by+/0hz03ZAgAAEWH48OGqrq7Whg0bgsu++OILSdI999yjzZs3B8uYz+fTokWLNH36dEnS/fffr0WLFsnn80mSjhw5os2bN+vuu+9WixYtdOedd2rOnDmqqqqSJNXW1urLL79slLn5NCIAAIgIHo9HWVlZeuKJJ/TCCy8oPj5eLVq0UGZmpjp16qTnnntOs2fPVkVFhQKBgO69917deuutkqRbb71VRUVFSk1NlcfjUVxcnJ577jl16tRJkvToo49q6dKluuWWW9SqVSvFxsZq0qRJwfUhzR0IBAIhv4olhYWFbo8ANfzjvRfy8d2maNumsgvedsLkttbmAIB/RWVlpVq2bOn2GGHBlEXXrl3PuT2nEQEAACyibAEAAFhE2QIAALCIsgUAAGARZQsAAMAiyhYAAIBF3GcLAACEPZ/Pp8mTJ0uSTp06pejo6OCXSt92223atm2boqOj5fF49MwzzygxMVE//OEPNW/ePPXv39/xetu3b9fUqVP1/vvvq2fPnlZnp2wBAIAGa8i9Ay/E+e4v6PV6tWPHDknSs88+q1atWum+++7TgQMH9OSTT2r79u1q3ry5fD7fBd35PTs7W4MHD1Z2drYefvjhxngL58RpRAAAELGKi4vl9XrVvHlzSV+Vss6dO3/rc86cOaPc3FwtW7ZMW7dutT4jZQsAAESskSNHqrCwUMOHD9fjjz+u3/3ud+d9zm9/+1uNGjVKCQkJateuneMLqhsbZQsAAESsVq1aafv27VqyZIni4+M1ffp0bdq06Vufk52drdTUVElSamqqsrOzrc7INVsAACCiRUdHKzk5WcnJyerTp49ee+214MX09ZWWlmrPnj06evSoPB6Pamtr5fF4NG/ePHk8HivzcWQLAABErLy8POXn5wcf/+lPf1L37t3Puf2bb76pO+64Q/v379e+fft04MABXXnlldq3b5+1GTmyBQAAIlZlZaXmzp2r06dPKyYmRldffbWWLFkSXP/jH/9YMTFf1Z2BAwfK5/PpgQceqPMa48aNU3Z2toYOHWplRk8gEAhYeeVGUFhY6PYIkJT68tEGbb91Sh9Lk0S2hnxM+nwfgQaAi62yslItW7Z0e4ywYMqia9eu59ye04gAAAAWUbYAAAAsomwBAABYRNkCAADnFcaXeF90Dc2CsgUAAM4rKipKNTU1bo/hupqaGkVFNaw+cesHAABwXrGxsaqqqlJ1dbW1m3+Gu0AgoKioKMXGxjboeZQtAABwXh6PRy1atHB7jIhE2QIAwKLaaRMbtH302jcsTQK3cM0WAACARZQtAAAAiyhbAAAAFlG2AAAALKJsAQAAWETZAgAAsIiyBQAAYBFlCwAAwKJGuanpwYMHtW7dOvn9ft1yyy1KS0urs/7Xv/61du7cqejoaLVu3VrTp09Xhw4dGmPXAAAAYS3kI1t+v19ZWVnKzMzUihUrtGfPHhUUFNTZ5uqrr9bixYu1bNkyDR06VBs3bgx1twAAABEh5LKVl5enzp07q1OnToqJiVFycrJyc3PrbHP99derefPmkqRevXrJ5/OFulsAAICIEPJpRJ/Pp/j4+ODj+Ph4HT9+/Jzbv/POOxowYIBxXU5OjnJyciRJixcvDnU0AAAA113UL6LetWuX8vPz9cQTTxjXp6SkKCUl5WKOBAAAYFXIpxG9Xq9KSkqCj0tKSuT1eh3bHTp0SK+//rpmz56tyy67LNTdAgAARISQy1ZCQoKKiopUXFysmpoa7d27V0lJSXW2+fjjj7V27VrNnj1bbdq0CXWXAAAAESPk04jR0dFKT0/XwoUL5ff7NXr0aF1xxRXatGmTEhISlJSUpI0bN6qqqkrLly+XJLVv316PPvpoyMMDAACEu0a5ZisxMVGJiYl1lk2ePDn487x58xpjNwAAABGHO8gDAABYRNkCAACwiLIFAABgEWULAADAIsoWAACARZQtAAAAiyhbAAAAFlG2AAAALKJsAQAAWETZAgAAsIiyBQAAYBFlCwAAwKJG+SJqAJeu2mkTG7R99No3LE0CAJGJI1sAAAAWUbYAAAAsomwBAABYRNkCAACwiLIFAABgEWULAADAIsoWAACARZQtAAAAiyhbAAAAFnEHeQAAIti2TWUXvO2EyW2tzYFz48gWAACARZQtAAAAiyhbAAAAFlG2AAAALKJsAQAAWETZAgAAsIiyBQAAYBFlCwAAwCLKFgAAgEWULQAAAIsoWwAAABZRtgAAACzii6gB4F9QO21ig7aPXvuGpUkAhDuObAEAAFhE2QIAALCIsgUAAGAR12wBAFyR+vLRBm2/dUofS5MAdlG2AAAIIw0toffGdLY0CRoLpxEBAAAsomwBAABYRNkCAACwiLIFAABgEWULAADAIsoWAACARZQtAAAAiyhbAAAAFlG2AAAALKJsAQAAWETZAgAAsIiyBQAAYBFlCwAAwKKYxniRgwcPat26dfL7/brllluUlpZWZ/2f//xnbdiwQZ9++qkyMjI0dOjQxtgtAABA2Av5yJbf71dWVpYyMzO1YsUK7dmzRwUFBXW2ad++ve6//34NHz481N0BAABElJCPbOXl5alz587q1KmTJCk5OVm5ubnq3r17cJuOHTtKkjweT6i7AwAAiCghH9ny+XyKj48PPo6Pj5fP5wv1ZQEAAC4JjXLNVmPJyclRTk6OJGnx4sUuTwMAABC6kMuW1+tVSUlJ8HFJSYm8Xu+/9FopKSlKSUkJdSQAAICwEfJpxISEBBUVFam4uFg1NTXau3evkpKSGmM2AACAiBfyka3o6Gilp6dr4cKF8vv9Gj16tK644gpt2rRJCQkJSkpKUl5enpYtW6YzZ87o97//vTZv3qzly5c3xvwAAABhrVGu2UpMTFRiYmKdZZMnTw7+3LNnT61evboxdgUAABBRuIM8AACARZQtAAAAiyhbAAAAFlG2AAAALKJsAQAAWETZAgAAsIiyBQAAYBFlCwAAwCLKFgAAgEWULQAAAIsa5et6AACwbdumsgZtP2FyWytzAA3FkS0AAACLOLIFABdB6stHL3jbrVP6WJwEwMXGkS0AAACLOLKFRsd1FUDTVTtt4oVvPGqJvUGAMMKRLQAAAIsoWwAAABZRtgAAACzimi0AjYpP3QFAXRzZAgAAsIiyBQAAYBFlCwAAwCLKFgAAgEWULQAAAIv4NCIA1/BtAwCaAo5sAQAAWETZAgAAsIiyBQAAYBFlCwAAwCLKFgAAgEWULQAAAIsoWwAAABZRtgAAACyibAEAAFhE2QIAALCIr+sJAV81AgAAzocjWwAAABZRtgAAACyibAEAAFhE2QIAALCIsgUAAGARZQsAAMAiyhYAAIBFlC0AAACLKFsAAAAWUbYAAAAs4ut6ACDM8FVgwKWFI1sAAAAWUbYAAAAsomwBAABYRNkCAACwiLIFAABgEWULAADAIsoWAACARZQtAAAAixrlpqYHDx7UunXr5Pf7dcsttygtLa3O+rNnz2rlypXKz8/X5ZdfroyMDHXs2LExdg0AABDWQj6y5ff7lZWVpczMTK1YsUJ79uxRQUFBnW3eeecdtWrVSs8995zGjx+vl19+OdTdAgAARISQy1ZeXp46d+6sTp06KSYmRsnJycrNza2zzYEDBzRq1ChJ0tChQ3XkyBEFAoFQdw0AABD2Qi5bPp9P8fHxwcfx8fHy+Xzn3CY6OlotW7bU559/HuquAQAAwl5YfRF1Tk6OcnJyJEmLFy92ZYbUl49e8LZbp/SxOEn4aCrvs6Ea8rsiRW6O0WvfaND2Wy3NEW7IxawhuZCJWVPJpSkJuWx5vV6VlJQEH5eUlMjr9Rq3iY+PV21trSorK3X55Zc7XislJUUpKSmhjgQAABA2Qj6NmJCQoKKiIhUXF6umpkZ79+5VUlJSnW0GDhyo9957T5L0wQcfqG/fvvJ4PKHuGgAAIOyFfGQrOjpa6enpWrhwofx+v0aPHq0rrrhCmzZtUkJCgpKSknTzzTdr5cqVevDBBxUXF6eMjIxGGB0AACD8Nco1W4mJiUpMTKyzbPLkycGfmzVrpv/+7/9ujF0BAABEFO4gDwAAYBFlCwAAwCLKFgAAgEWULQAAAIsoWwAAABZRtgAAACyibAEAAFhE2QIAALCIsgUAAGARZQsAAMAiyhYAAIBFlC0AAACLKFsAAAAWUbYAAAAsomwBAABYRNkCAACwiLIFAABgEWULAADAIsoWAACARTFuDxButk7p4/YIAADgEsKRLQAAAIsoWwAAABZRtgAAACyibAEAAFhE2QIAALCIsgUAAGARZQsAAMAiyhYAAIBFlC0AAACLKFsAAAAWUbYAAAAsomwBAABYRNkCAACwiLIFAABgEWULAADAIsoWAACARZQtAAAAiyhbAAAAFlG2AAAALKJsAQAAWETZAgAAsIiyBQAAYBFlCwAAwCLKFgAAgEWULQAAAIsoWwAAABZRtgAAACyibAEAAFhE2QIAALCIsgUAAGARZQsAAMAiyhYAAIBFlC0AAACLKFsAAAAWUbYAAAAsignlyRUVFVqxYoVOnTqlDh06aObMmYqLi3Nst3DhQh0/flx9+vTRY489FsouAQAAIkpIR7ays7PVr18//exnP1O/fv2UnZ1t3G7ixImaMWNGKLsCAACISCGVrdzcXI0cOVKSNHLkSOXm5hq369evn1q0aBHKrgAAACJSSKcRy8vL1a5dO0lS27ZtVV5eHtIwOTk5ysnJkSQtXrw4pNcCAAAIB+ctW0899ZTKysocy//93/+9zmOPxyOPxxPSMCkpKUpJSQnpNQAAAMLJecvWvHnzzrmuTZs2Ki0tVbt27VRaWqrWrVs36nAAAACRLqRrtpKSkvT+++9Lkt5//30NGjSoUYYCAAC4VIRUttLS0nTo0CE99NBDOnz4sNLS0iRJH330kVavXh3cbv78+Vq+fLkOHz6s++67TwcPHgxltwAAABHDEwgEAm4PcS6FhYVujwCcU+rLRxu0/dYpfSxNAgBwW9euXc+5jjvIAwAAWETZAgAAsIiyBQAAYBFlCwAAwCLKFgAAgEWULQAAAIsoWwAAABZRtgAAACyibAEAAFhE2QIAALCIsgUAAGARZQsAAMAiyhYAAIBFlC0AAACLKFsAAAAWUbYAAAAsomwBAABYRNkCAACwiLIFAABgEWULAADAIsoWAACARZQtAAAAiyhbAAAAFlG2AAAALKJsAQAAWETZAgAAsIiyBQAAYBFlCwAAwCLKFgAAgEWULQAAAIsoWwAAABZRtgAAACzyBAKBgNtDnEthYaHbIwAAAJxX165dz7mOI1sAAAAWUbYAAAAsomwBAABYRNkCAACwiLIFAABgEWULAADAIsoWAACARZQtAAAAiyhbAAAAFlG2AAAALKJsAQAAWETZAgAAsIiyBQAAYBFlCwAAwCJPIBAIuD0EAADApYojWxfgsccec3uEsEQuZuRiRi5OZGJGLmbkYhYJuVC2AAAALKJsAQAAWETZugApKSlujxCWyMWMXMzIxYlMzMjFjFzMIiEXLpAHAACwiCNbAAAAFlG2AAAALKJsAQAAWETZOoeysjLl5+crPz9fZWVlbo8T1qqqqtweAWGuoqLC7RHC0oEDB9weISzx++J08uRJffDBByooKHB7FNecOXPG7RH+ZTFuDxBuPvnkE61du1aVlZXyer2SpJKSErVq1UpTp05Vjx49XJ4w/MycOVMvvPCC22O44m9/+5vWrFkjn8+nAQMGaMqUKYqLi5MkPf7443r66addnvDiO3r0qNasWSOPx6Pp06fr1VdfVXFxsWpqajRz5kz17t3b7RFdsW/fvjqPA4GAsrKyVFtbK0kaMmSIG2O5bsuWLbrjjjskSQUFBVq6dKlqamokSRkZGerVq5eb47nmySef1MyZM9W6dWvt2rVLW7Zs0XXXXafXXntNKSkpuu2229we8aKbOnWq+vbtq2HDhmnIkCFq1aqV2yNdMMpWPatWrdJ//ud/Ov4FP3bsmF544QUtXbrUpcnc9etf/9q4PBAINOkjW2vXrtWkSZPUq1cv7dy5U/Pnz9fs2bPVuXPn4F+iTc2GDRs0c+ZMVVVVafHixXrkkUfUp08f5efna926dXrqqafcHtEV//M//6P+/furdevWwWXV1dX6/e9/L6nplq39+/cHy9ZLL72ke+65RzfeeKPy8vK0fv16LViwwOUJ3XH69Ong78pbb72lBQsW6PLLL1d1dbXmzJnTJMtWt27dNG7cOO3Zs0cbN25Unz59NGzYMA0aNEjNmjVze7xvRdmqp7q62vh/Ur17927SpeKVV17RhAkTFB0d7VjXlO8eUlVVpQEDBkiSJk6cqB49emjRokWaMWOGPB6Pu8O5pLa2VldeeaUkqXXr1urTp48kqUePHvryyy/dHM1VTz31lH75y1+qZ8+euvXWWyVJf/rTn3T//fe7PFn4KC0t1Y033ihJ6tmzZ5P+fYmOjpbP55PX61VsbKyaN28uSbrsssvk9/tdns4dMTExGjhwoAYOHKgvv/xSBw4c0N69e5WVlaX+/fvrJz/5idsjnhNlq54BAwbo6aef1siRIxUfHy/pq9OI77//fvAv1abommuu0eDBg42nUd955x0XJgoflZWVatmypSTp+uuv16xZs/Tss8822etOvlm+77zzzjrrvj491BT17NlTc+fO1fbt2/Xkk09qypQpTbaQf9Pf//53PfPMMwoEAiopKVF1dXWwWDTVo8OSdPfdd2vBggUaMmSIunfvrp/+9Kfq37+/jh49qlGjRrk9niu++d+WZs2aKTk5WcnJyaqsrNT+/ftdnOz8uKmpwR/+8Afl5ubK5/NJkrxer5KSkpSYmOjyZO4pLCxUXFxcnVMgXysrK1Pbtm0v/lBhYPfu3erYsaPjOqR//OMf+tWvfqX77rvPpcncc+DAAfXr1y/4F+bXTp48qX379ik1NdWlycKHz+fT+vXrlZ+fr5UrV7o9jqv+/Oc/13nco0cPxcbGqqysTB988IHGjh3r0mTuq6ys1O7du1VYWCi/3y+v16tBgwapW7dubo/mijfeeEMTJ050e4x/CWULAADAIm790ABr1qxxe4SwRC5m5OJEJmbkYkYuZuTiFO6ZcM1WPee6ziYQCOgPf/jDRZ4mfJCLGbk4kYkZuZiRixm5OEVyJpSteqZOnaoOHTrUuRDP4/EoEAiovLzcxcncRS5m5OJEJmbkYkYuZuTiFMmZULbq6dSpk+bPn6/27ds71k2fPt2FicIDuZiRixOZmJGLGbmYkYtTJGfCNVv1jBs37pyHKiP1UxCNgVzMyMWJTMzIxYxczMjFKZIz4dOIAAAAFnFk6wKE+6cc3EIuZuTiRCZm5GJGLmbk4hQpmVC2LkB+fr7bI4QlcjEjFycyMSMXM3IxIxenSMmEsnUBTHdNB7mcC7k4kYkZuZiRixm5OEVKJlyzBQAAYBG3fqjH7/frvffe0759++Tz+RQVFaUuXbpozJgx6tu3r9vjuYZczMjFiUzMyMWMXMzIxSmSM+HIVj3PP/+82rdvrxtuuEEffPCBWrRooeuuu05bt25VUlKSbrvtNrdHdAW5mJGLE5mYkYsZuZiRi1NEZxJAHbNmzarzODMzMxAIBAJffvllICMjw42RwgK5mJGLE5mYkYsZuZiRi1MkZ8IF8vVER0fr5MmTkr76lENMzFdnWi+77DI3x3IduZiRixOZmJGLGbmYkYtTJGfCNVv1/OhHP9KTTz6pmJgY+f1+ZWRkSJJOnz6tgQMHujuci8jFjFycyMSMXMzIxYxcnCI5E67ZMggEAvr8888j5iOlFwu5mJGLE5mYkYsZuZiRi1OkZsKRLYPCwkLl5ubK5/NJkrxer5KSktS9e3eXJ3MXuZiRixOZmJGLGbmYkYtTpGbCka16srOztWfPHg0bNkxer1eS5PP5gsvS0tLcHdAl5GJGLk5kYkYuZuRiRi5OEZ2JO9flh6+HHnoocPbsWcfys2fPBh588EEXJgoP5GJGLk5kYkYuZuRiRi5OkZwJn0asx+PxqLS01LG8tLRUHo/HhYnCA7mYkYsTmZiRixm5mJGLUyRnwmnEeg4ePKisrCx16dJF8fHxkqR//OMfOnnypKZOnaoBAwa4O6BLyMWMXJzIxIxczMjFjFycIjkTypaB3+9XXl5enQvwevbsqaiopn0gkFzMyMWJTMzIxYxczMjFKVIzoWxdgJycHKWkpLg9RtghFzNycSITM3IxIxczcnGKlEzCuwqGiR07drg9QlgiFzNycSITM3IxIxczcnGKlEwoWxeAg39m5GJGLk5kYkYuZuRiRi5OkZIJpxEvQElJSfBiPPwTuZiRixOZmJGLGbmYkYtTpGTCka0L8PUf5LvvvuvyJOGFXMzIxYlMzMjFjFzMyMUpUjKhbDXA5s2b3R4hLJGLGbk4kYkZuZiRixm5OIV7Jnw3Yj0PP/ywcXkgEFB5eflFniZ8kIsZuTiRiRm5mJGLGbk4RXImlK16ysvLNWfOHLVq1arO8kAgoHnz5rk0lfvIxYxcnMjEjFzMyMWMXJwiORPKVj2JiYmqqqrS1Vdf7Vj3ne985+IPFCbIxYxcnMjEjFzMyMWMXJwiORM+jQgAAGARF8gDAABYRNmq59NPP9WcOXM0ffp0rVmzRhUVFcF1jz/+uIuTuYtczMjFiUzMyMWMXMzIxSmSM6Fs1fOLX/xCkyZN0rJly9SlSxfNnz9fJ0+elCTV1ta6PJ17yMWMXJzIxIxczMjFjFycIjkTLpCvp6qqSgMGDJAkTZw4UT169NCiRYs0Y8YMeTwed4dzEbmYkYsTmZiRixm5mJGLUyRnwpEtg8rKyuDP119/vWbNmqWVK1fq1KlTLk7lPnIxIxcnMjEjFzNyMSMXp0jNhLJVT2pqqgoKCuosu+qqqzR//nwNHjzYpancRy5m5OJEJmbkYkYuZuTiFMmZcOsHAAAAi7hmq57Kykq9/vrrys3NVXl5uTwej9q0aaOkpCSlpaU57lzbVJCLGbk4kYkZuZiRixm5OEVyJhzZqmfhwoXq27evRo0apbZt20qSysrK9N577+nIkSOaO3euuwO6hFzMyMWJTMzIxYxczMjFKZIz4ZqteoqLi5WWlhb8g5Sktm3bKi0tLewvwLOJXMzIxYlMzMjFjFzMyMUpkjOhbNXToUMHbd26VWVlZcFlZWVlys7OVvv27d0bzGXkYkYuTmRiRi5m5GJGLk6RnAmnEeupqKhQdna2Dhw4oPLycklfNeeBAwcqLS1NcXFxLk/oDnIxIxcnMjEjFzNyMSMXp0jOhLJlcOLECZWUlKh3796KjY0NLj948GDwhmpNEbmYkYsTmZiRixm5mJGLU6RmwmnEen7zm99oyZIl2r59u2bNmqXc3NzguldeecXFydxFLmbk4kQmZuRiRi5m5OIUyZlw64d6du7cqWeeeUaxsbEqLi7W8uXLderUKY0bN05N+SAguZiRixOZmJGLGbmYkYtTJGdC2aonEAgED0127NhRTzzxhJ599lmdOnUq7P8wbSIXM3JxIhMzcjEjFzNycYrkTDiNWE+bNm30ySefBB/Hxsbqscce0+eff66//e1v7g3mMnIxIxcnMjEjFzNyMSMXp0jOhAvk6ykpKVF0dHSd+3h87ejRo+rTp8/FHyoMkIsZuTiRiRm5mJGLGbk4RXImlC0AAACLOI0IAABgEWULAADAIsoWgEvKqlWr9Oqrr7o9BgAEUbYANElPPPGEdu7c6fYYAJoAyhYAAIBF3NQUQET7+OOPtXr1ahUVFenGG2+Ux+OR9NWX1q5cuVLHjx+X3+/Xtddeq2nTpik+Pl6vvPKK/vKXv+j48eNav369Ro0apalTp+rEiRN68cUXlZ+fr9atW2vy5MlKTk52+R0CiHQc2QIQsWpqarR06VLddNNNevHFF/Xd735X+/btk/TV3aZHjRql559/Xs8//7yaNWumrKwsSdKdd96p6667Tunp6XrppZc0depUVVVVacGCBRo+fLh+8YtfKCMjQ1lZWSooKHDzLQK4BFC2AESsY8eOqba2VuPHj1dMTIyGDh2qhIQESdLll1+uoUOHqnnz5mrRooV+8IMf6C9/+cs5X+vDDz9Uhw4dNHr0aEVHR+uaa67RkCFD9Lvf/e5ivR0AlyhOIwKIWKWlpfJ6vcFTh5LUvn17SVJ1dbU2bNiggwcP6syZM5KkL774Qn6/X1FRzv/PPHXqlI4fP6577rknuKy2tlYjRoyw+yYAXPIoWwAiVrt27eTz+RQIBIKFq6SkRJ07d9a2bdtUWFioRYsWqW3btvrkk080e/bs4BfWfrOgSVJ8fLy+853vaN68eRf9fQC4tHEaEUDE6t27t6KiovTWW2+ppqZG+/btU15eniSpqqpKzZo1U8uWLVVRUaHXXnutznPbtGmjv//978HHAwcOVFFRkXbt2qWamhrV1NQoLy+Pa7YAhIzvRgQQ0T766COtWbNGJ0+e1I033ihJ6tKli2699Vb97Gc/00cffSSv16vvf//7Wrt2rV555RVFR0fr2LFjWrVqlU6fPq2bbrpJ6enpKiws1IYNG5SXl6dAIKCrrrpKd999t66++mp33ySAiEbZAgAAsIjTiAAAABZRtgAAACyibAEAAFhE2QIAALCIsgUAAGARZQsAAMAiyhYAAIBFlC0AAACLKFsAAAAW/T94/WxAWRBiFQAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 720x432 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.rcParams['figure.figsize'] = [10,6]\n",
    "\n",
    "mean_scores = parsed_and_scored_news.groupby(['ticker','date']).mean()\n",
    "\n",
    "mean_scores = mean_scores.unstack()\n",
    "\n",
    "mean_scores = mean_scores.xs('compound',axis='columns').transpose()\n",
    "\n",
    "mean_scores.plot(kind = 'bar')\n",
    "plt.grid()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "03538d7e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
